# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qt6::Core)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::Core
add_library(Qt6::Core STATIC IMPORTED)

set_target_properties(Qt6::Core PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION;QT_COORD_TYPE"
  INTERFACE_COMPILE_DEFINITIONS "QT_CORE_LIB"
  INTERFACE_COMPILE_OPTIONS "-fPIC;\$<\$<OR:\$<CXX_COMPILER_ID:GNU>,\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>,\$<CXX_COMPILER_ID:IntelLLVM>>:-ffunction-sections;-fdata-sections>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtCore;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Platform;\$<LINK_ONLY:Qt6::GlobalConfigPrivate>;\$<LINK_ONLY:WrapZLIB::WrapZLIB>;\$<LINK_ONLY:Qt6::PlatformModuleInternal>;WrapAtomic::WrapAtomic;\$<LINK_ONLY:Qt6::ZlibPrivate>;\$<LINK_ONLY:m>;\$<LINK_ONLY:WrapPCRE2::WrapPCRE2>;\$<LINK_ONLY:WrapRt::WrapRt>;\$<LINK_ONLY:WrapRt::WrapRt>;\$<LINK_ONLY:WrapRt::WrapRt>"
  INTERFACE_LINK_OPTIONS "\$<\$<OR:\$<CXX_COMPILER_ID:GNU>,\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>,\$<CXX_COMPILER_ID:IntelLLVM>>:-Wl,--gc-sections>"
  INTERFACE_QT_COORD_TYPE "double"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/./metatypes/qt6core_metatypes.json>"
  QT_DISABLED_PRIVATE_FEATURES "system_doubleconversion;broken_threadlocal_dtors;dladdr;glib;icu;winsdkicu;jemalloc;journald;system_libb2;system_pcre2;poll_pollts;poll_poll;poll_select;qqnx_pps;slog2;syslog;vxpipedrv;backtrace;cxx20_format;cxx23_stacktrace;cpp_winrt;lttng;etw;ctf;poll_exit_on_error;openssl_hash;use_bfd_linker;use_gold_linker;use_lld_linker;use_mold_linker;android_style_assets;developer_build;private_tests;doc_snippets;debug;elf_private_full_version;no_direct_extern_access;lsx;lasx;mips_dsp;mips_dspr2;neon;arm_crc32;arm_crypto;arm_sve;localtime_s;force_system_libs;system_zlib;stdlib_libcpp;dbus;dbus_linked;gui;printsupport;sql;testlib;widgets;xml;libudev;openssl;dlopen;relocatable;stack_clash_protection;libcpp_hardening"
  QT_DISABLED_PUBLIC_FEATURES "glib;jemalloc;cpp_winrt;library;itemmodel;proxymodel;sortfilterproxymodel;identityproxymodel;transposeproxymodel;concatenatetablesproxymodel;stringlistmodel;animation;gestures;timezone_tzdb;shared;cross_compile;pkg_config;debug_and_release;separate_debug_info;appstore_compliant;simulator_and_device;rpath;force_asserts;framework;cxx20;cxx2a;cxx2b;cxx2c;wasm_simd128;wasm_exceptions;wasm_jspi;zstd;concurrent;dbus;openssl_linked;opensslv11;opensslv30"
  QT_ENABLED_PRIVATE_FEATURES "clock_gettime;copy_file_range;doubleconversion;futimens;getauxval;getentropy;inotify;linkat;memmem;memrchr;mimetype_database;poll_ppoll;posix_sem;posix_shm;pthread_clockjoin;pthread_condattr_setclock;pthread_timedjoin;renameat2;sysv_sem;sysv_shm;dup3;accept4;sha3_fast;hijricalendar;timezone_locale;datetimeparser;forkfd_pidfd;pcre2;gc_binaries;reduce_exports;x86intrin;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani;localtime_r;posix_fallocate;force_bundled_libs;network;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;libstdcpp_assertions;relro_now_linker;largefile;enable_new_dtags;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani"
  QT_ENABLED_PUBLIC_FEATURES "clock_monotonic;cxx11_future;cxx17_filesystem;inotify;std_atomic64;mimetype;regularexpression;sharedmemory;shortcut;systemsemaphore;xmlstream;xmlstreamreader;xmlstreamwriter;textdate;datestring;process;processenvironment;temporaryfile;settings;filesystemwatcher;filesystemiterator;translation;easingcurve;jalalicalendar;islamiccivilcalendar;timezone;commandlineparser;cborstreamreader;cborstreamwriter;permissions;threadsafe_cloexec;version_tagging;static;reduce_relocations;signaling_nan;thread;future;test_gui;static;plugin_manifest;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;libstdcpp_assertions;relro_now_linker;static;no_pkg_config;reduce_exports;reduce_relocations;no_gui;no_widgets"
  QT_QMAKE_PRIVATE_CONFIG "pcre2;largefile;enable_new_dtags;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani"
  QT_QMAKE_PUBLIC_CONFIG "static;plugin_manifest;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;libstdcpp_assertions;relro_now_linker"
  QT_QMAKE_PUBLIC_QT_CONFIG "threadsafe_cloexec;static;no_pkg_config;reduce_exports;reduce_relocations;no_gui;no_widgets"
  _qt_config_module_name "core"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtCore"
  _qt_module_interface_name "Core"
  _qt_module_relative_include_dir "../../../include/QtCore"
  _qt_package_name "Qt6Core"
  _qt_package_version "6.10.2"
  _qt_private_module_target_name "CorePrivate"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Qt6CoreTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Platform" "Qt6::GlobalConfigPrivate" "Qt6::PlatformModuleInternal" "Qt6::ZlibPrivate" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
